# Generated by Django 5.2.5 on 2025-09-09 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='メッセージ内容を入力してください（最大200文字）', max_length=200, verbose_name='メッセージ内容')),
                ('is_pinned', models.BooleanField(default=False, help_text='このメッセージがピン留めされているかどうか', verbose_name='ピン留め')),
                ('pin_duration_hours', models.PositiveIntegerField(blank=True, choices=[(12, '12時間'), (24, '24時間'), (168, '1週間')], help_text='ピン留め期間を時間単位で指定', null=True, verbose_name='ピン留め期間（時間）')),
                ('pinned_at', models.DateTimeField(blank=True, help_text='ピン留めされた日時', null=True, verbose_name='ピン留め日時')),
                ('pin_expires_at', models.DateTimeField(blank=True, help_text='ピン留めが自動解除される日時', null=True, verbose_name='ピン留め期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
                'ordering': ['-is_pinned', '-pin_duration_hours', '-pinned_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('thumbs_up', '👍'), ('heart', '❤️'), ('laughing', '😂'), ('surprised', '😮')], max_length=20, verbose_name='リアクション種類')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='リアクション日時')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bulletin_board.message', verbose_name='対象メッセージ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='リアクションユーザー')),
            ],
            options={
                'verbose_name': 'リアクション',
                'verbose_name_plural': 'リアクション',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'message', 'reaction_type')},
            },
        ),
    ]
