# Generated by Django 5.2.5 on 2025-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='show_name',
            field=models.BooleanField(default=False, help_text='チェックすると名前を表示して投稿します（基本は匿名）', verbose_name='名前を表示'),
        ),
    ]
