# Generated by Django 5.2.5 on 2025-09-03 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_type', models.CharField(choices=[('clock_in', '出勤'), ('clock_out', '退勤'), ('break_start', '休憩開始'), ('break_end', '休憩終了')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='timeclock_t_user_id_a0529f_idx'), models.Index(fields=['user', 'clock_type', 'timestamp'], name='timeclock_t_user_id_c135d9_idx')],
            },
        ),
    ]
