# Generated by Django 5.2.5 on 2025-09-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timerecord',
            options={'ordering': ['-timestamp'], 'verbose_name': '打刻記録', 'verbose_name_plural': '打刻記録'},
        ),
    ]
