# Generated by Django 5.2.5 on 2025-09-04 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0003_monthlytarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidLeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('grant', '付与'), ('use', '使用'), ('expire', '時効消滅')], max_length=10, verbose_name='記録タイプ')),
                ('days', models.PositiveIntegerField(verbose_name='日数')),
                ('grant_date', models.DateField(help_text='付与された日付（使用時は付与された日を記録）', verbose_name='付与日')),
                ('expiry_date', models.DateField(help_text='この有給休暇の有効期限（付与日から2年後）', verbose_name='有効期限')),
                ('used_date', models.DateField(blank=True, help_text='有給休暇を使用した日（付与・時効消滅時はNull）', null=True, verbose_name='使用日')),
                ('description', models.CharField(blank=True, help_text='付与理由や使用理由などの備考', max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_leave_records', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '有給休暇記録',
                'verbose_name_plural': '有給休暇記録',
                'ordering': ['-grant_date', '-created_at'],
            },
        ),
    ]
