# Generated by Django 5.2.5 on 2025-09-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0004_paidleaverecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidleaverecord',
            name='cancellation_date',
            field=models.DateField(blank=True, help_text='付与取消が行われた日（付与・使用・時効消滅時はNull）', null=True, verbose_name='取消日'),
        ),
        migrations.AlterField(
            model_name='paidleaverecord',
            name='record_type',
            field=models.CharField(choices=[('grant', '付与'), ('use', '使用'), ('expire', '時効消滅'), ('cancel', '付与取消')], max_length=10, verbose_name='記録タイプ'),
        ),
        migrations.AlterField(
            model_name='paidleaverecord',
            name='used_date',
            field=models.DateField(blank=True, help_text='有給休暇を使用した日（付与・取消・時効消滅時はNull）', null=True, verbose_name='使用日'),
        ),
    ]
