# Generated by Django 5.2.5 on 2025-09-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0005_paidleaverecord_cancellation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidleaverecord',
            name='cancellation_date',
        ),
        migrations.AddField(
            model_name='paidleaverecord',
            name='expired',
            field=models.BooleanField(default=False, help_text='この記録が時効により無効化されている場合True', verbose_name='時効フラグ'),
        ),
        migrations.AlterField(
            model_name='paidleaverecord',
            name='record_type',
            field=models.CharField(choices=[('grant', '付与'), ('use', '使用')], max_length=10, verbose_name='記録タイプ'),
        ),
    ]
