# Generated by Django 5.2.5 on 2025-09-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_wage',
            field=models.PositiveIntegerField(blank=True, help_text='ユーザーの時給を設定します（任意）。', null=True, verbose_name='時給'),
        ),
    ]
