# Generated by Django 5.2.5 on 2025-09-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_hourly_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_monthly_income',
            field=models.PositiveIntegerField(blank=True, help_text='ユーザーの目標月収を設定します（任意）。', null=True, verbose_name='目標月収'),
        ),
    ]
