# Generated by Django 5.2.5 on 2025-09-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_target_monthly_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='target_monthly_income',
        ),
    ]
