# Generated by Django 5.2.5 on 2025-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_target_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_paid_leave',
            field=models.PositiveIntegerField(default=0, help_text='現在付与されている有給休暇の残日数。', verbose_name='現在の有給休暇日数'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, help_text='有給休暇計算の基準日となります。', null=True, verbose_name='雇用開始日'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_work_days',
            field=models.PositiveIntegerField(default=5, help_text='週の所定労働日数（1-7日）。有給休暇の付与日数計算に使用します。', verbose_name='週の所定労働日数'),
        ),
    ]
