# Generated by Django 5.2.5 on 2025-09-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_current_paid_leave_user_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_leave_grant_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='有給休暇の付与日スケジュール。{付与回数: "YYYY-MM-DD"} の形式。入社日に基づいて自動計算されます。', verbose_name='有給休暇付与スケジュール'),
        ),
    ]
