# Generated by Django 5.2.5 on 2025-09-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_paid_leave_grant_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paid_leave_grant_schedule',
            field=models.JSONField(blank=True, default=list, help_text='有給休暇の付与日リスト。["YYYY-MM-DD", ...] の形式。入社日に基づいて自動計算されます。', verbose_name='有給休暇付与スケジュール'),
        ),
    ]
