# Generated by Django 5.2.5 on 2025-10-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_paid_leave_grant_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hourly_wage',
        ),
    ]
