# Generated by Django 5.2.5 on 2025-09-16 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('total_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cached_daily_minutes', models.JSONField(blank=True, default=dict, help_text="{'1': 480, '2': 420, ...} 形式で保存")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-total_minutes'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='leaderboard_user_id_939474_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
