# Generated by Django 5.2.5 on 2025-09-16 13:13

from django.db import migrations, models


def convert_decimal_to_int(apps, schema_editor):
    """既存のDecimalデータをIntegerに変換"""
    LeaderboardEntry = apps.get_model('leaderboard', 'LeaderboardEntry')
    for entry in LeaderboardEntry.objects.all():
        # Decimal型から整数に変換（小数部分は切り捨て）
        if entry.total_minutes:
            entry.total_minutes = int(entry.total_minutes)
            entry.save(update_fields=['total_minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['rank', '-total_minutes'], 'verbose_name': 'ランキングエントリ', 'verbose_name_plural': 'ランキングエントリ'},
        ),
        # 既存データを変換してからフィールドを変更
        migrations.RunPython(convert_decimal_to_int, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='total_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
