# Generated by Django 5.2.5 on 2025-09-22 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スキル名')),
                ('description', models.TextField(verbose_name='説明')),
                ('category', models.CharField(choices=[('technical', '技術スキル'), ('customer_service', '接客スキル'), ('management', '管理スキル')], max_length=20, verbose_name='スキルカテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'スキル',
                'verbose_name_plural': 'スキル',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='グレード名')),
                ('hourly_wage', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='時給')),
                ('level', models.IntegerField(verbose_name='レベル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_skills', models.ManyToManyField(blank=True, to='salary.skill', verbose_name='必要習得スキル')),
            ],
            options={
                'verbose_name': '給与グレード',
                'verbose_name_plural': '給与グレード',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='申告日')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='処理日')),
                ('comment', models.TextField(blank=True, verbose_name='申告理由・処理コメント')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL, verbose_name='処理者')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.skill', verbose_name='スキル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スキル習得申告',
                'verbose_name_plural': 'スキル習得申告',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='適用日')),
                ('reason', models.TextField(blank=True, verbose_name='変更理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='変更者')),
                ('salary_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.salarygrade', verbose_name='給与グレード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー給与グレード履歴',
                'verbose_name_plural': 'ユーザー給与グレード履歴',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['user', '-effective_date'], name='salary_user_user_id_cee476_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_date', models.DateField(verbose_name='習得日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_skills', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.skill', verbose_name='スキル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー習得スキル',
                'verbose_name_plural': 'ユーザー習得スキル',
                'ordering': ['user', 'skill'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
