# Generated by Django 5.2.5 on 2025-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygrade',
            name='next_possible_grades',
            field=models.ManyToManyField(blank=True, help_text='このグレードから昇進可能な次のグレードを選択してください', to='salary.salarygrade', verbose_name='次に昇進可能なグレード'),
        ),
    ]
