# Generated by Django 5.2.5 on 2025-09-24 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salarygrade_next_possible_grades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('skill_create', 'スキル作成'), ('skill_edit', 'スキル編集'), ('skill_grant', 'スキル手動付与'), ('skill_revoke', 'スキル取り消し'), ('grade_create', 'グレード作成'), ('grade_edit', 'グレード編集'), ('grade_change', 'ユーザーグレード変更'), ('application_approve', '申告承認'), ('application_reject', '申告却下')], max_length=20, verbose_name='操作種別')),
                ('description', models.TextField(verbose_name='操作内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
            options={
                'verbose_name': '管理者操作ログ',
                'verbose_name_plural': '管理者操作ログ',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='salary_admi_timesta_5710a8_idx'), models.Index(fields=['admin_user', '-timestamp'], name='salary_admi_admin_u_24e077_idx')],
            },
        ),
    ]
