# Generated by Django 5.2.5 on 2025-09-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_adminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygrade',
            name='description',
            field=models.TextField(default='', verbose_name='説明'),
        ),
    ]
